name: github pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '1.3.x'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - run: go generate gen.go

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Github Actions
          author_email: klim0v-sergey@yandex.ru
          message: "generate files"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}